#!/bin/sh
#
# Copyright (C) 2020 Daniel Lenski
#
# This file is part of openconnect.
#
# This is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public License
# as published by the Free Software Foundation; either version 2.1 of
# the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

# This test uses LD_PRELOAD
PRELOAD=1
SERV="${SERV:-../src/ocserv}"
srcdir=${srcdir:-.}
top_builddir=${top_builddir:-..}

. `dirname $0`/common.sh

########################################
# Verify that we cannot connect to a server offering only RSA key exchange
# IF --pfs is specified to require perfect forward secrecy, but that we
# CAN connect if it is not specified.
########################################

echo "Testing against server without PFS... "

# Need to disable TLS 1.3 here because GnuTLS v3.6.13 is allowing non-RSA KX with TLS 1.3, even with -KX-ALL
# But can't use -VERS-TLS1.3 here, because it's not known to earlier versions of GnuTLS.
PORT=4569
TLS_PRIORITIES="LEGACY:%SERVER_PRECEDENCE:%COMPAT:-VERS-TLS-ALL:+VERS-TLS1.0:+VERS-TLS1.1:+VERS-TLS1.2:-KX-ALL:+RSA"
update_config test-obsolete-server-crypto.config
launch_simple_sr_server -d 1 -f -c $CONFIG
PID=$!
wait_server $PID

echo -n "Connecting with --pfs... "
( echo "test" | LD_PRELOAD=libsocket_wrapper.so $OPENCONNECT -q $ADDRESS:$PORT -u test --servercert=d66b507ae074d03b02eafca40d35f87dd81049d3 --pfs --cookieonly >/dev/null 2>&1) &&
	fail $PID "Connected successfully when we shouldn't"

echo ok

echo -n "Connecting without --pfs... "
( echo "test" | LD_PRELOAD=libsocket_wrapper.so $OPENCONNECT -q $ADDRESS:$PORT -u test --servercert=d66b507ae074d03b02eafca40d35f87dd81049d3 --cookieonly >/dev/null 2>&1) ||
	fail $PID "Could not connect and obtain cookie without --pfs"

echo ok

cleanup

exit 0
